# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor/bundle']


# Site Settings
title: "FOSS4GNL 2026"
email: "foss4g@osgeo.nl"
description: "FOSS4GNL conference website 2026"
baseurl: ""
url: "https://foss4g.nl"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"


# Organizer Info
organizerName: "OSGeo.nl"
organizerAlternateName: "Open Source Geo Nederland"
organizerDescription: "..."
organizerEmail: "foss4g@osgeo.nl"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://osgeo.nl/"

# Head
metaKeywords: "event, osgeo, conferentie, open source, geo, gis, RUG, geographic, nederland, Groningen, osgeonl"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {link: "https://pretalx.com/foss4gnl/schedule/", text: "Programma"}
 - {link: "https://pretix.eu/foss4gnl/2026/", text: "Tickets"}
 - {permalink: "#partners", text: "Onze sponsors"}


rightNavigationButtons:
#   - {link: "https://pretix.eu/foss4gnl/2025/", text: "Tickets"}

# About Block (voor urls gebruik enkele aanhalingstekens  ' ' )
aboutTitle: "Over FOSS4GNL 2026"
aboutDescription: "Ook in 2026 is er uiteraard weer een FOSS4GNL. Dit jaar zijn we te gast in het Groothandelshuis, het voormalige gebouw van de Vroom & Dreesmann in Groningen. <br><br>
De organisatie is dit jaar in samenwerking met de <a href='https://www.rug.nl/jantina-tammes-school/''>Jantina Tammes School of Digital Society, Technology and AI</a>. 
<br><br>
De FOSS4GNL 2026 wordt gehouden op twee dagen, elk met een eigen invulling:<br></p>
<ul>
<li>Woensdag 8 juli: workshopdag en icebreakerparty</li>
<li>Donderdag 9 juli: het hart van de FOSS4G, de conferentiedag</li>
</ul>
<p>Locatie: het Groothandelshuis aan de Grote Markt in hartje Groningen.<br><br>
De ticketverkoop is geopend tot begin juli. Je mag zelf je ticketprijs bepalen, de suggestie (de kosten die we aan horeca voor je maken) is 35 euro. Zakelijke bezoekers adviseren we voor de conferentie een <i>bedrijfsticket<i> te kopen: daarvan kan je er ook meer tegelijk bestellen.<br><br>


"
# aboutLogo:
#  - { image: "", text: "logo foss4g 2026"}


# Statistic Block
statisticBlockImage: "220512_216_Omnia.jpg"
statisticBlock:
 - {count: "9", specialCharacter: "", info: "workshops", detail: ""}
 - {count: "2", specialCharacter: "", info: "keynotes", detail: ""}
 - {count: "45", specialCharacter: "", info: "sessies", detail: ""}
 - {count: "5", specialCharacter: "", info: "parallele tracks", detail: ""}

# Latest News Block
latestNewsTitle: "Nieuws"

# Location Block
locationBlockTitle: "Locatie"
eventLocationName: "Groothandelshuis"
eventLocationLink: ""
eventStreetAddress: ""
eventAddressLocality: "Groningen"
eventAddressLocalityRegion: "Groningen"
eventPostalCode: ""
eventAddressCountry: "Nederland"
eventStartTime: "2025-07-08T10:00"
eventDoorTime: "09:00"
eventEndTime: "2025-07-09T18:00"
eventPlaceCoordinates: "53.2190461, 6.5663137"
eventPlaceLongitude: 6.5663137
eventPlaceLatitude: 53.2190461
mapCenterCoordinates: "53.2190461, 6.5663137"
mapMobileCenterCoordinates: "53.2190461, 6.5663137"

# Partners Block
partnersTitle: "Sponsors"
becomeSponsorLink: "mailto:foss4g@osgeo.nl"
sponsorsButtonText: "Word een sponsor"


# Organizers Block
organizersTitle: "Organisatie"
becomeSponsorLink: "mailto:foss4g@osgeo.nl"
sponsorsButtonText: "Word een sponsor"


# Tickets Block
ticketsTitle: "Prijslijst"
ticketsInfo: ""
ticketsOffers:
 -
  name: "Conferentiedag 9 juli"
  price: ""
  priceCurrency: "Donatie"
  ticketsNumber: "?"
  buyButtonLink: "https://www.eventbrite.nl/e/tickets-foss4gnl-2019-60886980598"
  buyButtonText: "Koop nu"
  soldOut: false
  soldOutText: "Uitverkocht"
  validFrom: "2019-04-23T00:00"
  validThrough: "2019-06-20T00:00"
 -

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=osgeonl", icon: "twitter"}
 - {linkedin: "osgeo-nl", icon: "linkedin"}
footerBlocks:
-
  title: "Contact"
  links:
   - {link: "mailto:foss4g@osgeo.nl", text: "foss4g@osgeo.nl"}

-
  title: "Links"
  links:
    - {link: "https://osgeo.nl/", text: "OSGeo.nl"}
    - {link: "https://wiki.osgeo.org/wiki/Nederlands/", text: "Wiki"}
    - {link: "https://www.osgeo.org/code_of_conduct/", text: "Code of Conduct"}

-
  title: "Previous events"
  links:
   - {link: "https://2017.foss4g.nl", text: "FOSS4GNL 2017"}
   - {link: "https://2018.foss4g.nl", text: "FOSS4GNL 2018"}
   - {link: "https://2019.foss4g.nl", text: "FOSS4GNL 2019"}
   - {link: "https://2021.foss4g.nl", text: "FOSS4GNL 2021"}
   - {link: "https://2023.foss4g.nl", text: "FOSS4GNL 2023" }
   - {link: "https://2024.foss4g.nl", text: "FOSS4G BE&NL 2024" }
   - {link: "https://2025.foss4g.nl", text: "FOSS4GNL 2025" }

# Blog
blogTitle: ""
blogCommentsEnabled: false
discusShortName: "osgeo"

# Speakers List Block
showSessions: true

